### ISSUE TITLE
Issue adding datepicker to Formview

### ISSUE THREAD

**Issue by rdh9616** [shellscape/Brew#5]
The load handler does not get triggered when the controls are added to a Formview control.

Here is an example.

```
    <form id="form1" runat="server">

        <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>

        <asp:FormView ID="FormView1" ItemType="System.Int32" SelectMethod="GetDataSource" runat="server">
            <ItemTemplate>
                <brew:Datepicker ID="t1" runat="server" For="TextBox1"></brew:Datepicker>
                <input type="text" id="TextBox1" runat="server" />
            </ItemTemplate>
        </asp:FormView>

        <script runat="server" language="c#">
            public List<int> GetDataSource()
            {
                return new List<int> { 1 };
            }    
        </script>

    </form>
```

Thanks,

Ray

**Comment by shellscape** [comment]
Please add the missing information from https://github.com/shellscape/Brew/wiki/Reporting-errors-or-issues

And which load handler are you speaking of?

**Comment by rdh9616** [comment]
This is in Development.

Development OS: Windows 8 Enterprise (6.2.9200.0)
IDE: Visual Studio 2012 Premium
Project Type: WebSite project 
WebServer: Visual Studio development server.

The LoadHandler I was referring to was in Widget.cs below...

```
        private static void LoadHandler(object sender, EventArgs ea) {
            var page = sender as Page;
            var brew = page.FindControl("__brew");

            if (brew == null) {
                brew = new HtmlGenericControl("brew") { ID = "__brew", ClientIDMode = ClientIDMode.Static };
                brew.Controls.Add(new LiteralControl("\n"));
                page.Form.Controls.Add(brew);
            }

            if (ScriptManager.GetCurrent(page) == null) {
                page.Form.Controls.AddAt(0, new ScriptManager() { ID = "scriptmanager" });
            }

            ScriptManager.RegisterOnSubmitStatement(page, typeof(Widget), "Brew.Script", Properties.Resources.SubmitScript);
        }

```

The exception is thrown inside the render method of Widget.cs because the following assignment returns null.

```

        protected override void Render(HtmlTextWriter writer) {

            var brew = this.Page.Form.FindControl("__brew");

...
...
```

To reproduce the issue you can use the snippet in my first post.

Here is the stack strace.

   at Brew.Webforms.Widget.Render(HtmlTextWriter writer) in c:\Users\rhorner\Documents\GitHub\Brew\src\Brew.Webforms\Widget.cs:line 119
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderChildren(HtmlTextWriter writer)
   at System.Web.UI.WebControls.TableCell.RenderContents(HtmlTextWriter writer)
   at System.Web.UI.WebControls.WebControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderChildren(HtmlTextWriter writer)
   at System.Web.UI.WebControls.WebControl.RenderContents(HtmlTextWriter writer)
   at System.Web.UI.WebControls.WebControl.Render(HtmlTextWriter writer)
   at System.Web.UI.WebControls.FormViewRow.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.WebControls.Table.RenderContents(HtmlTextWriter writer)
   at System.Web.UI.WebControls.WebControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderChildren(HtmlTextWriter writer)
   at System.Web.UI.WebControls.WebControl.RenderContents(HtmlTextWriter writer)
   at System.Web.UI.WebControls.FormView.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer)
   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)
   at System.Web.UI.HtmlControls.HtmlForm.Render(HtmlTextWriter output)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.HtmlControls.HtmlForm.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderChildren(HtmlTextWriter writer)
   at System.Web.UI.Page.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Thanks,

Ray

**Comment by shellscape** [comment]
Thanks. I'll look into this tomorrow for you.

**Comment by shellscape** [comment]
OK so the quick fix is to put a control on the page in the main <form> that looks like this:

```
<brew id="__brew" runat="server"></brew>
```

It's only a fix to prevent the error. I haven't figured out how to inject into the page lifecycle yet when brew controls are in the form view.

An actual fix in the lib is going to take me a while longer. Any child controls inside of a FormView are taken out of the normal page event flow, which creates the problem you're seeing.

**Comment by shellscape** [comment]
Got the issue resolved with a little help from Modules. This fix will be in the next version, but in the mean time, you can add code to your project to work around the issue:

Add to your web.config:

``` xml
<system.webServer>
    <modules>
        <add name="EventHookModule" type="Brew.Webforms.EventHookModule" preCondition="managedHandler"/>
    </modules>
</system.webServer>
```

If you're running on IIS6, you'll have to place a similar declaration in <system.web><httpModules>

Add the following class in App_Code:

``` csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.UI;

namespace Brew.Webforms {

    public class EventHookModule : IHttpModule {

        public void Init(HttpApplication context) {
            context.PreRequestHandlerExecute += new EventHandler(context_PreRequestHandlerExecute);
        }

        void context_PreRequestHandlerExecute(object sender, EventArgs e) {
            Page page = HttpContext.Current.CurrentHandler as Page;
            if (page != null) {
                page.PreInit += new EventHandler(page_PreInit);
            }
        }

        void page_PreInit(object sender, EventArgs e) {
            Page page = sender as Page;
            if (page == null) {
                return;
            }

            var type = typeof(Widget);
            var @event = page.GetType().GetEvent("Load");
            var method = type.GetMethod("LoadHandler", BindingFlags.NonPublic | BindingFlags.Static);
            Delegate handler = Delegate.CreateDelegate(@event.EventHandlerType, method);

            @event.RemoveEventHandler(page, handler);
            @event.AddEventHandler(page, handler);

        }

        public void Dispose() {  }
    }
}
```
